version: "3.9"
services:
  earth:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    user: "1000:1000"
    container_name: earth
    tty: true
    working_dir: /app/
    volumes: 
      - ./:/app/
    ports: 
      - "127.0.0.1:3021:3000"
    networks:
      - omar-local
networks:
  omar-local:
    driver: bridge
